# Generated by Django 2.0.9 on 2018-12-04 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('limit_balance', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female')])),
                ('education', models.IntegerField(choices=[(1, 'graduate_school'), (2, 'university'), (3, 'high school;'), (4, 'other')])),
                ('marriage', models.IntegerField(choices=[(1, 'married'), (2, 'single'), (3, 'others')])),
                ('age', models.IntegerField()),
                ('pay_0', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('pay_2', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('pay_3', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('pay_4', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('pay_5', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('pay_6', models.IntegerField(choices=[(-1, 'pay'), (1, '1month_dalay'), (2, '2months_dlay')])),
                ('bill_amt_1', models.IntegerField()),
                ('pay_amt_1', models.IntegerField()),
                ('pay_amt_2', models.IntegerField()),
                ('pay_amt_3', models.IntegerField()),
                ('pay_amt_4', models.IntegerField()),
                ('pay_amt_5', models.IntegerField()),
                ('pay_amt_6', models.IntegerField()),
                ('result', models.IntegerField()),
                ('proba', models.FloatField()),
                ('comment', models.CharField(max_length=200)),
                ('registered_date', models.DateField(default=datetime.date(2018, 12, 4))),
            ],
        ),
    ]
