# Generated by Django 2.0.9 on 2018-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='proba',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='result',
            field=models.IntegerField(blank=True),
        ),
    ]
