# Generated by Django 2.0.9 on 2018-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_auto_20181204_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='proba',
            field=models.FloatField(default=0.0),
        ),
    ]
